server.port=${ORCHESTRATOR_SERVICE_PORT:8080}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/aegis_orchestrator_db
spring.datasource.username=${ORCHESTRATOR_POSTGRES_USERNAME}
spring.datasource.password=${ORCHESTRATOR_POSTGRES_PASSWORD}
spring.datasource.hikari.maximum-pool-size=50
spring.datasource.hikari.minimum-idle=10
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.rabbitmq.host=${AEGIS_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${AEGIS_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${AEGIS_RABBITMQ_USERNAME}
spring.rabbitmq.password=${AEGIS_RABBITMQ_PASSWORD}

spring.mvc.problemdetails.enabled=true

management.tracing.sampling.probability=0.1
management.tracing.export.zipkin.endpoint=${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}
spring.rabbitmq.template.observation-enabled=true
spring.rabbitmq.listener.simple.observation-enabled=true
jdbc.datasource-proxy.query.enable-logging=true

# Expose the Prometheus scraping endpoint
management.endpoints.web.exposure.include=health,info,prometheus
# Tag all metrics with the application name so we can filter them in Grafana
management.metrics.tags.application=${spring.application.name}
# Write logs to a local directory
logging.file.name=logs/${spring.application.name}.log