spring.application.name=provider-simulator
server.port=${PROVIDER_SIMULATOR_PORT:8081}

spring.mvc.problemdetails.enabled=true

spring.threads.virtual.enabled=true

management.tracing.sampling.probability=1.0
management.tracing.export.zipkin.endpoint=${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}