spring.application.name=provider-simulator
server.port=${PROVIDER_SIMULATOR_PORT:8081}

spring.mvc.problemdetails.enabled=true

spring.threads.virtual.enabled=true

management.tracing.sampling.probability=1.0
management.tracing.export.zipkin.endpoint=${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}

# Expose the Prometheus scraping endpoint
management.endpoints.web.exposure.include=health,info,prometheus
# Tag all metrics with the application name so we can filter them in Grafana
management.metrics.tags.application=${spring.application.name}
# Write logs to a local directory
logging.file.name=logs/${spring.application.name}.log