package io.github.kxng0109.ledgerservice.service;

import io.github.kxng0109.ledgerservice.entity.TransactionLog;
import io.github.kxng0109.ledgerservice.enums.TransactionStatus;
import io.github.kxng0109.ledgerservice.exception.DuplicateTransactionException;
import io.github.kxng0109.ledgerservice.repository.TransactionLogRepository;
import io.github.kxng0109.ledgerservice.request.dto.CreditRequest;
import io.github.kxng0109.ledgerservice.response.dto.DebitResponse;
import io.github.kxng0109.ledgerservice.response.dto.RefundResponse;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.amqp.rabbit.annotation.RabbitListener;
import org.springframework.amqp.rabbit.core.RabbitTemplate;
import org.springframework.data.redis.core.StringRedisTemplate;
import org.springframework.stereotype.Service;

import java.math.BigDecimal;
import java.time.Duration;
import java.util.Optional;

/**
 * Facade service that orchestrates ledger operations such as debits and credits while
 * providing idempotency, concurrency control, and integration with messaging and
 * persistence layers.
 *
 * <ul>
 *   <li>Debits are processed synchronously via {@link #handleDebit(String, String, BigDecimal)}.</li>
 *   <li>Credits are consumed asynchronously from the {@code credit.queue} RabbitMQ queue
 *       and handled by {@link #handleCredit(CreditRequest)}.</li>
 *   <li>Redis locks prevent simultaneous processing of the same transaction for a given
 *       user and idempotency key.</li>
 *   <li>Transaction outcomes are persisted in {@link TransactionLogRepository} and
 *       communicated through RabbitMQ using {@link #sendRefundResponse(RefundResponse)}.</li>
 * </ul>
 *
 * The service depends on the following collaborators:
 * <ul>
 *   <li>{@link StringRedisTemplate} – for acquiring and releasing distributed locks.</li>
 *   <li>{@link TransactionLogRepository} – for looking up existing transaction logs.</li>
 *   <li>{@link CoreLedgerService} – for the actual business logic of debit and credit
 *       processing.</li>
 *   <li>{@link RabbitTemplate} – for publishing refund responses.</li>
 * </ul>
 *
 * All public methods are designed to be thread‑safe and to guarantee that a request
 * identified by an {@code idempotencyKey} is processed at most once. If a duplicate
 * request is detected, the previously recorded result is returned without re‑executing
 * the core ledger operation.
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class LedgerFacadeService {

	private final StringRedisTemplate stringRedisTemplate;
	private final TransactionLogRepository transactionLogRepository;
	private final CoreLedgerService coreLedgerService;
	private final RabbitTemplate rabbitTemplate;

	/**
	 * Handles a debit request for a given user while ensuring idempotency and preventing
	 * concurrent processing of the same transaction.
	 *
	 * @param userId         the unique identifier of the user whose account is to be debited
	 * @param idempotencyKey a unique key provided by the caller to guarantee that repeated
	 *                       requests with the same key are processed only once
	 * @param amount         the monetary amount to be debited from the user's account; must be a
	 *                       non‑negative {@link BigDecimal}
	 * @return a {@link DebitResponse} containing the result of the debit operation,
	 * either retrieved from a previous transaction log or generated by processing
	 * the debit through the core ledger service
	 */
	public DebitResponse handleDebit(
			String userId,
			String idempotencyKey,
			BigDecimal amount
	) {
		// check the db if the transaction log exists
		Optional<TransactionLog> transactionLog = transactionLogRepository.findByReferenceId(idempotencyKey);
		// If it exists, then return it
		if (transactionLog.isPresent()) {
			return constructDebitResponse(transactionLog.get());
		}

		String redisLockKey = "lock:debit:" + userId + ":" + idempotencyKey;

		// Try and acquire the redis lock
		Boolean lockAcquired = stringRedisTemplate.opsForValue().setIfAbsent(
				redisLockKey,
				"LOCKED",
				Duration.ofMinutes(1)
		);

		// IF we can't then that means the transaction is currently ongoing
		if (Boolean.FALSE.equals(lockAcquired)) throw new DuplicateTransactionException(
				"Transaction is currently processing. Please try again.",
				idempotencyKey
		);

		// We have obtained the redis lock
		// wrapped in a try...finally block so that no matter what happens in the coreLedgerService,
		// the redis lock gets deleted
		try {
			// let's call the coreLedgerService to handle the actual transaction
			return constructDebitResponse(
					coreLedgerService.processDebit(
							userId,
							idempotencyKey,
							amount
					)
			);
		} finally {
			// Redis lock gets deleted no matter what,
			// but only after the coreLedgerService is done
			stringRedisTemplate.delete(redisLockKey);
		}
	}

	/**
	 * Processes a credit request received from the {@code credit.queue} RabbitMQ queue.
	 *
	 * <p>The method performs the following steps:
	 * <ul>
	 *   <li>Checks the database for an existing {@link TransactionLog} using the request's idempotency key.
	 *       If found, a {@link RefundResponse} based on the existing transaction is sent and processing ends.</li>
	 *   <li>Attempts to acquire a Redis lock identified by the user ID and idempotency key to ensure
	 *       that only one instance of the transaction is processed concurrently.</li>
	 *   <li>If the lock cannot be obtained, a {@link DuplicateTransactionException} is thrown, indicating
	 *       that the transaction is already in progress.</li>
	 *   <li>When the lock is acquired, delegates the actual credit operation to {@code coreLedgerService.processCredit}.
	 *       The resulting {@link TransactionLog} is used to build and send a {@link RefundResponse}.</li>
	 *   <li>Regardless of success or failure, the Redis lock is released in a {@code finally} block.</li>
	 *   <li>Any unexpected exception is caught, logged, and results in a {@link RefundResponse} with a
	 *       {@link TransactionStatus#FAILED} status being sent.</li>
	 * </ul>
	 *
	 * @param request the credit request containing the user identifier, idempotency key, and amount to be credited
	 */
	@RabbitListener(queues = "credit.queue")
	public void handleCredit(
			CreditRequest request
	) {
		try {
			// check the db if the transaction log exists
			Optional<TransactionLog> transactionLog = transactionLogRepository.findByReferenceId(
					request.idempotencyKey()
			);
			// If it exists, then return it
			if (transactionLog.isPresent()) {
				TransactionLog txLog = transactionLog.get();

				RefundResponse refundResponse = new RefundResponse(
						txLog.getStatus().toString(),
						txLog.getReferenceId(),
						txLog.getAccount().getUserId()
				);
				sendRefundResponse(refundResponse);
			}

			String redisLockKey = "lock:credit:" + request.userId() + ":" + request.idempotencyKey();

			// Try and acquire the redis lock
			Boolean lockAcquired = stringRedisTemplate.opsForValue().setIfAbsent(
					redisLockKey,
					"LOCKED",
					Duration.ofMinutes(1)
			);

			// IF we can't then that means the transaction is currently ongoing
			if (Boolean.FALSE.equals(lockAcquired)) throw new DuplicateTransactionException(
					"Transaction is currently processing. Please try again.",
					request.idempotencyKey()
			);

			// We have obtained the redis lock
			// wrapped in a try...finally block so that no matter what happens in the coreLedgerService,
			// the redis lock gets deleted
			try {
				// let's call the coreLedgerService to handle the actual transaction
				TransactionLog txLog = coreLedgerService.processCredit(
						request.userId(),
						request.idempotencyKey(),
						request.amount()
				);

				RefundResponse refundResponse = new RefundResponse(
						txLog.getStatus().toString(),
						txLog.getReferenceId(),
						txLog.getAccount().getUserId()
				);
				sendRefundResponse(refundResponse);
			} finally {
				// Redis lock gets deleted no matter what,
				// but only after the coreLedgerService is done
				stringRedisTemplate.delete(redisLockKey);
			}
		} catch (Exception e) {
			log.error("An error occurred while processing credit request. {}", e.getMessage(), e);
			sendRefundResponse(
					new RefundResponse(
							TransactionStatus.FAILED.toString(),
							request.idempotencyKey(),
							request.userId()
					)
			);
		}
	}

	/**
	 * Sends a {@code RefundResponse} message to the configured RabbitMQ exchange using the
	 * predefined routing key. This method utilizes the {@code rabbitTemplate} to serialize the
	 * {@code refundResponse} object and publish it to the {@code refund.response.exchange}
	 * exchange, making it available for downstream consumers that are bound to the
	 * {@code refund.response.routing.key} routing key.
	 *
	 * @param refundResponse the response containing refund details to be sent; must not be {@code null}
	 */
	private void sendRefundResponse(RefundResponse refundResponse) {
		rabbitTemplate.convertAndSend(
				"refund.response.exchange",
				"refund.response.routing.key",
				refundResponse
		);
	}

	/**
	 * Creates a {@link DebitResponse} DTO from the given {@link TransactionLog}.
	 *
	 * @param transactionLog the transaction log containing the details of the debit operation;
	 *                       must not be {@code null}
	 * @return a {@code DebitResponse} populated with the transaction identifier, reference identifier,
	 * amount, status, and creation timestamp extracted from {@code transactionLog}
	 */
	private DebitResponse constructDebitResponse(TransactionLog transactionLog) {
		return DebitResponse.builder()
		                    .transactionId(transactionLog.getId())
		                    .referenceId(transactionLog.getReferenceId())
		                    .amount(transactionLog.getAmount())
		                    .status(transactionLog.getStatus())
		                    .timestamp(transactionLog.getCreatedAt())
		                    .build();
	}
}
