package io.github.kxng0109.ledgerservice.service;

import io.github.kxng0109.ledgerservice.config.RabbitConfig;
import io.github.kxng0109.ledgerservice.entity.TransactionLog;
import io.github.kxng0109.ledgerservice.enums.OperationType;
import io.github.kxng0109.ledgerservice.enums.TransactionStatus;
import io.github.kxng0109.ledgerservice.exception.DuplicateTransactionException;
import io.github.kxng0109.ledgerservice.repository.TransactionLogRepository;
import io.github.kxng0109.ledgerservice.request.dto.CreditRequest;
import io.github.kxng0109.ledgerservice.response.dto.DebitResponse;
import io.github.kxng0109.ledgerservice.response.dto.RefundResponse;
import io.micrometer.observation.annotation.Observed;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.amqp.rabbit.annotation.RabbitListener;
import org.springframework.amqp.rabbit.core.RabbitTemplate;
import org.springframework.data.redis.core.StringRedisTemplate;
import org.springframework.stereotype.Service;

import java.math.BigDecimal;
import java.time.Duration;
import java.util.Optional;

/**
 * Facade service that coordinates ledger operations across persistence, caching,
 * and messaging layers. It guarantees idempotent processing of debit and credit
 * requests and protects against concurrent execution of the same logical
 * transaction by using a Redis‑backed distributed lock.
 *
 * <p>Typical usage patterns are:
 * <ul>
 *   <li>Invoking {@link #handleDebit(String, String, BigDecimal)} from a
 *       REST controller to debit a user's account.</li>
 *   <li>Allowing Spring AMQP to invoke {@link #handleCredit(CreditRequest)} and
 *       {@link #handleTimeoutRefund(CreditRequest)} as asynchronous message listeners.</li>
 * </ul>
 *
 * <p>All public methods are thread‑safe; the only mutable state is the transient
 * Redis lock which is scoped to a specific {@code userId} and {@code idempotencyKey}.
 *
 * @see TransactionLogRepository
 * @see CoreLedgerService
 * @see StringRedisTemplate
 * @see RabbitTemplate
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class LedgerFacadeService {

	private final StringRedisTemplate stringRedisTemplate;
	private final TransactionLogRepository transactionLogRepository;
	private final CoreLedgerService coreLedgerService;
	private final RabbitTemplate rabbitTemplate;
	private final RabbitConfig rabbitConfig;

	/**
	 * Handles a debit request for a given user while ensuring idempotency and preventing
	 * concurrent processing of the same transaction.
	 *
	 * @param userId         the unique identifier of the user whose account is to be debited
	 * @param idempotencyKey a unique key provided by the caller to guarantee that repeated
	 *                       requests with the same key are processed only once
	 * @param amount         the monetary amount to be debited from the user's account; must be a
	 *                       non‑negative {@link BigDecimal}
	 * @return a {@link DebitResponse} containing the result of the debit operation,
	 * either retrieved from a previous transaction log or generated by processing
	 * the debit through the core ledger service
	 */
	public DebitResponse handleDebit(
			String userId,
			String idempotencyKey,
			BigDecimal amount
	) {
		// check the db if the transaction log exists
		Optional<TransactionLog> transactionLog = transactionLogRepository.findByReferenceId(idempotencyKey);
		// If it exists, then return it
		if (transactionLog.isPresent()) {
			return constructDebitResponse(transactionLog.get());
		}

		String redisLockKey = "lock:debit:" + userId + ":" + idempotencyKey;

		// Try and acquire the redis lock
		Boolean lockAcquired = stringRedisTemplate.opsForValue().setIfAbsent(
				redisLockKey,
				"LOCKED",
				Duration.ofMinutes(1)
		);

		// IF we can't then that means the transaction is currently ongoing
		if (Boolean.FALSE.equals(lockAcquired)) throw new DuplicateTransactionException(
				"Transaction is currently processing. Please try again.",
				idempotencyKey
		);

		// We have obtained the redis lock
		// wrapped in a try...finally block so that no matter what happens in the coreLedgerService,
		// the redis lock gets deleted
		try {
			// let's call the coreLedgerService to handle the actual transaction
			return constructDebitResponse(
					coreLedgerService.processDebit(
							userId,
							idempotencyKey,
							amount
					)
			);
		} finally {
			// Redis lock gets deleted no matter what,
			// but only after the coreLedgerService is done
			stringRedisTemplate.delete(redisLockKey);
		}
	}

	/**
	 * Processes a credit request received from the {@code credit.queue} RabbitMQ queue.
	 * <p>
	 * The method implements an idempotent workflow:
	 * <ul>
	 *   <li>First checks the {@link TransactionLogRepository} for an existing {@link TransactionLog}
	 *       identified by {@code request.idempotencyKey()}. If found, a {@link RefundResponse}
	 *       reflecting the stored status is sent back immediately.</li>
	 *   <li>If no prior log exists, a Redis lock is acquired using a composite key
	 *       {@code "lock:credit:" + request.userId() + ":" + request.idempotencyKey()}.
	 *       The lock guarantees that concurrent consumers cannot process the same transaction
	 *       simultaneously. The lock expires after one minute to avoid dead‑locks.</li>
	 *   <li>When the lock is obtained, the request is handed to {@link CoreLedgerService#processCredit}
	 *       which performs the actual ledger update and persists a new {@link TransactionLog}.</li>
	 *   <li>Regardless of success or failure, the Redis lock is released in a {@code finally} block,
	 *       ensuring no lock leakage.</li>
	 *   <li>Any exception thrown during processing results in a {@link RefundResponse} with
	 *       {@link TransactionStatus#FAILED} and is logged for diagnostics.</li>
	 * </ul>
	 * </p>
	 *
	 * @param request the credit request payload; must be non‑null and contain a valid
	 *                {@code userId}, {@code idempotencyKey}, and {@code amount}.
	 * @throws DuplicateTransactionException if a lock cannot be obtained because another
	 *                                       instance is already processing a transaction with the same
	 *                                       {@code userId} and {@code idempotencyKey}.
	 * @throws IllegalArgumentException      if {@code request} violates validation constraints
	 *                                       such as a negative {@code amount}.
	 * @see RefundResponse
	 * @see TransactionLog
	 * @see CoreLedgerService#processCredit(String, String, BigDecimal)
	 */
	@RabbitListener(queues = "credit.queue")
	@Observed(name = "ledger.facade.handleCredit")
	public void handleCredit(
			CreditRequest request
	) {
		try {
			// check the db if the transaction log exists
			Optional<TransactionLog> transactionLog = transactionLogRepository.findByReferenceId(
					request.idempotencyKey()
			);
			// If it exists, then return it
			if (transactionLog.isPresent()) {
				TransactionLog txLog = transactionLog.get();

				RefundResponse refundResponse = new RefundResponse(
						txLog.getStatus().toString(),
						txLog.getReferenceId(),
						txLog.getAccount().getUserId()
				);
				sendRefundResponse(refundResponse);
			}

			String redisLockKey = "lock:credit:" + request.userId() + ":" + request.idempotencyKey();

			// Try and acquire the redis lock
			Boolean lockAcquired = stringRedisTemplate.opsForValue().setIfAbsent(
					redisLockKey,
					"LOCKED",
					Duration.ofMinutes(1)
			);

			// IF we can't then that means the transaction is currently ongoing
			if (Boolean.FALSE.equals(lockAcquired)) throw new DuplicateTransactionException(
					"Transaction is currently processing. Please try again.",
					request.idempotencyKey()
			);

			// We have obtained the redis lock
			// wrapped in a try...finally block so that no matter what happens in the coreLedgerService,
			// the redis lock gets deleted
			try {
				// let's call the coreLedgerService to handle the actual transaction
				TransactionLog txLog = coreLedgerService.processCredit(
						request.userId(),
						request.idempotencyKey(),
						request.amount()
				);

				RefundResponse refundResponse = new RefundResponse(
						txLog.getStatus().toString(),
						txLog.getReferenceId(),
						txLog.getAccount().getUserId()
				);
				sendRefundResponse(refundResponse);
			} finally {
				// Redis lock gets deleted no matter what,
				// but only after the coreLedgerService is done
				stringRedisTemplate.delete(redisLockKey);
			}
		} catch (Exception e) {
			log.error("An error occurred while processing credit request. {}", e.getMessage(), e);
			sendRefundResponse(
					new RefundResponse(
							TransactionStatus.FAILED.toString(),
							request.idempotencyKey(),
							request.userId()
					)
			);
		}
	}

	/**
	 * Processes a timeout notification for a refund operation received from the
	 * {@code timeout.refund.response.queue} RabbitMQ queue.
	 *
	 * <p>The method first derives the original debit {@code referenceId} by
	 * replacing the {@code "refund-ledger-timeout-"} prefix in the {@link CreditRequest#idempotencyKey()}
	 * with {@code "transfer-"}. It then queries the {@link TransactionLogRepository}
	 * for a {@link TransactionLog} whose {@code referenceId} matches the derived value
	 * and whose {@code operationType} is {@link OperationType#DEBIT}. If such a debit
	 * transaction exists, a compensating credit is issued via {@code handleCredit};
	 * otherwise a {@link RefundResponse} with a {@link TransactionStatus#NOT_FOUND}
	 * status is published.</p>
	 *
	 * <p>This method is invoked by Spring AMQP as a message listener; each
	 * invocation is independent and the implementation does not maintain mutable
	 * shared state, making it safe for concurrent execution provided that the
	 * underlying {@code transactionLogRepository} and messaging infrastructure are
	 * themselves thread‑safe.</p>
	 *
	 * @param request the refund timeout payload; must be non‑null and contain a
	 *                valid {@code idempotencyKey} and {@code userId}
	 */
	@RabbitListener(queues = "timeout.refund.response.queue")
	@Observed(name = "ledger.facade.handleTimeoutRefund")
	public void handleTimeoutRefund(
			CreditRequest request
	) {

		// We need to check if the debit was actually made
		// We check to see if that referenceId exists
		// We replace the "refund-ledger-timeout" we receive with "transfer" since it's what we use for debits
		String referenceId = request.idempotencyKey().replace("refund-ledger-timeout-", "transfer-");

		// Does a referenceId with type "DEBIT" exists?
		Optional<TransactionLog> transactionLog = transactionLogRepository.findByReferenceIdAndOperationType(
				referenceId,
				OperationType.DEBIT
		);

		// It does? Then trigger a refund
		if (transactionLog.isPresent()) {
			rabbitTemplate.convertAndSend(
					rabbitConfig.CREDIT_EXCHANGE_NAME,
					rabbitConfig.CREDIT_ROUTING_KEY,
					request
			);
			return;
		}

		// It doesn't? Then send a "NOT_FOUND" status refund response
		sendRefundResponse(
				RefundResponse.builder()
				              .status(TransactionStatus.NOT_FOUND.toString())
				              .referenceId(request.idempotencyKey())
				              .userId(request.userId())
				              .build()
		);
	}

	/**
	 * Sends a {@code RefundResponse} message to the configured RabbitMQ exchange using the
	 * predefined routing key. This method utilizes the {@code rabbitTemplate} to serialize the
	 * {@code refundResponse} object and publish it to the {@code refund.response.exchange}
	 * exchange, making it available for downstream consumers that are bound to the
	 * {@code refund.response.routing.key} routing key.
	 *
	 * @param refundResponse the response containing refund details to be sent; must not be {@code null}
	 */
	private void sendRefundResponse(RefundResponse refundResponse) {
		rabbitTemplate.convertAndSend(
				rabbitConfig.REFUND_RESPONSE_EXCHANGE_NAME,
				rabbitConfig.REFUND_RESPONSE_ROUTING_KEY,
				refundResponse
		);
	}

	/**
	 * Creates a {@link DebitResponse} DTO from the given {@link TransactionLog}.
	 *
	 * @param transactionLog the transaction log containing the details of the debit operation;
	 *                       must not be {@code null}
	 * @return a {@code DebitResponse} populated with the transaction identifier, reference identifier,
	 * amount, status, and creation timestamp extracted from {@code transactionLog}
	 */
	private DebitResponse constructDebitResponse(TransactionLog transactionLog) {
		return DebitResponse.builder()
		                    .transactionId(transactionLog.getId())
		                    .referenceId(transactionLog.getReferenceId())
		                    .amount(transactionLog.getAmount())
		                    .status(transactionLog.getStatus())
		                    .timestamp(transactionLog.getCreatedAt())
		                    .build();
	}
}
