spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/aegis_ledger_db
spring.datasource.username=${LEDGER_POSTGRES_USERNAME}
spring.datasource.password=${LEDGER_POSTGRES_PASSWORD}
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.connection-timeout=5000
spring.jpa.hibernate.ddl-auto=validate

spring.data.redis.host=${AEGIS_REDIS_HOST:localhost}
spring.data.redis.port=${AEGIS_REDIS_PORT:6379}

spring.rabbitmq.host=${AEGIS_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${AEGIS_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${AEGIS_RABBITMQ_USERNAME}
spring.rabbitmq.password=${AEGIS_RABBITMQ_PASSWORD}

spring.mvc.problemdetails.enabled=true
